config/routes.rb
Rails.application.routes.draw do
  get 	'sessions/new'
  get  	'users/new'
  root  'static_pages#home'
  get 	'/help',		      to: 'static_pages#help'					 
  get	'/signup',				  to: 'users#new'
  post	'/signup',				to: 'users#create'
  get	'/login' ,			   	to: 'sessions#new'
  post	'/login' ,				to: 'sessions#create'
  delete '/logout',				to: 'sessions#destroy' 
  resources :users do
    get '/work-list',    to: 'lists#work'
    get '/home-list',    to: 'lists#home'
    resources :lists  do
      member do  
      get  :purpose
      end
    end
  end
  resources :password_resets, only:[:new, :create, :edit, :update]


  
end

app/models/list.rb
class List < ApplicationRecord
	enum purpose: [:home, :work]
	belongs_to :user
	validates :user_id, presence: true
	validates :title, presence: true, length: { maximum: 100}
	validates :text, presence: true, length: { maximum: 500}
	validates :date_due, presence: true

	def self.my_order
		order(created_at: :desc)			
	end
	
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :set_list, only: [:new,:edit, :create, :update, :purpose, :work, :home]
	
	def new
		@list = current_user.lists.build
	end

	def work
		@list = @user.lists.work.my_order	
	end

	def home
		@list = @user.lists.home	
	end

	def show
		@user = User.find(params[:user_id])
		@list = List.find(params[:id])		
	end

	def edit	
		@user = User.find(params[:user_id])
		@list = List.find(params[:id])		
	end	

	def create
		@list = @user.lists.build(list_params)	
		if @list.save
			flash[:success] = "List created!"
			redirect_to user_url(current_user)
		else
			render 'new'
		end
	end

	def update
		@list = List.find(params[:id])
		if @list.update_attributes(list_params)
			flash[:success] = "List updated."
			redirect_to user_url(current_user)
		else
			render 'edit'
		end		
	end

	def destroy
		 @list = List.find(params[:id])
		 @list.destroy
		 flash[:success] = "List deleted."
		 redirect_to user_url(current_user)
	end

	def purpose
		@list = List.find(params[:id])	
		@list.home? ? @list.work! : @list.home!
		flash[:success] = "Purpose  has been changed." 
		redirect_to user_url(@user)
	end

	private

			def set_list
				@user = User.find(params[:user_id])
			end

			def list_params
				params.require(:list).permit(:text, :title, :date_due, :purpose)	
			end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_new_form.html.erb
<%= form_for([@user,@list]) do |f| %>
	 <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :text %>
  <%= text_area(:list,:text, cols: 24, row: 20, class: 'form-control')  %>

	<%= select "list","purpose", options_for_select([["Home", "home"], ["Work", "work"]]), {}, { class: 'form-control'} %>

  <%= f.label :date_due %>
  <%= f.text_field :date_due, class: 'form-control' %>


  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/lists/edit.html.erb
<% provide(:title, "Edit list") %>
<% provide(:button_text, 'Save changes') %>
<div class="new-forms container-fluid">
	<div class="row justify-content-md-center">
  		<div class="col-md-6">
  			<h1 class="m-5 text-center">Update your list</h1>
    		<%= render 'new_form' %>
  		</div>
	</div>
</div>

app/views/lists/home.html.erb
<% provide(:title, 'User List Home') %>
<h2>"Home List"</h2>

<% @list.each do |item| %>
<h4><%= item.title %></h4>
<h5><%= item.text %></h5>
<h6><%= item.created_at %></h6>
<h5><%= link_to item.purpose, purpose_user_list_path(@user, item.id) %></h5>
<h5><%= link_to 'edit',   edit_user_list_path(@user, item.id)  %></h5>
<h5><%= link_to 'delete', user_list_path(@user, item.id), method: :delete, data: { confirm: 'Are you sure?'} %></h5>

<br>
<% end %>


<p><%= link_to 'New List', new_user_list_path(@user.id) %></p>

app/views/lists/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create List') %>
<div class="new-forms container-fluid">
	<div class="row justify-content-md-center">
		<div class="col-md-6">
			<h1 class="m-5 text-center">Create List</h1>
			<%= render 'new_form' %>
		</div>	
	</div>
</div>

app/views/lists/show.html.erb
<div class="show-list-main">
	<div class="mt-5 container-fluid">
		<div class="row justify-content-md-center">
			<div class="col-md-8">
				<h1>Your list:</h1>
				<div class="card">
  				<div class="card-header">
   				 <h3>title: <%= @list.title %></h3>
 					 </div>
  				<ul class="list-group list-group-flush">
  			  	<li class="list-group-item">List: <%= @list.text %></li>
   				 	<li class="list-group-item">create: <%= time_ago_in_words(@list.created_at)%> ago</li>
   					<li class="list-group-item">date due: <%= time_ago_in_words(@list.date_due)%>, <%= @list.date_due %></li>
  				</ul>
				</div>
				<div class="mt-5 pb-2">
					<%= link_to 'Back',   user_path(@user), class:"float-left btn btn-outline-primary"  %>
					<%= link_to '<i class="fas fa-edit"></i>'.html_safe,   edit_user_list_path(@user, @list.id), class:" edit-button-show float-right"  %>
				</div>
				<div class="clearfix mb-3"></div>
			</div>
		</div>
	</div>
</div>

app/views/lists/work.html.erb
<% provide(:title, 'User List Work') %>
<h2>"Work List"</h2>

<% @list.each do |item| %>
<h4><%= item.title %></h4>
<h5><%= item.text %></h5>
<h6><%= item.created_at %></h6>
<h5><%= link_to item.purpose, purpose_user_list_path(@user, item.id) %></h5>
<h5><%= link_to 'edit',   edit_user_list_path(@user, item.id)  %></h5>
<h5><%= link_to 'delete', user_list_path(@user, item.id), method: :delete, data: { confirm: 'Are you sure?'} %></h5>
<br>
<% end %>


<p><%= link_to 'New List', new_user_list_path(@user.id) %></p>