config/routes.rb
Rails.application.routes.draw do
  get 	'sessions/new'
  get  	'users/new'
  root  'static_pages#home'
  get 	'/help',		      to: 'static_pages#help'					 
  get	'/signup',				  to: 'users#new'
  post	'/signup',				to: 'users#create'
  get	'/login' ,			   	to: 'sessions#new'
  post	'/login' ,				to: 'sessions#create'
  delete '/logout',				to: 'sessions#destroy' 
  resources :users do
    get '/work-list',    to: 'lists#work'
    get '/home-list',    to: 'lists#home'
    resources :lists  do
      member do  
      get  :purpose
      end
    end
  end
  resources :password_resets, only:[:new, :create, :edit, :update]


  
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<p class="mt-4 text-center">&copy; LuMa <span id="year"><%= Date.today.year %></span></p>	
	</div>	
</footer>  

app/views/layouts/_header.html.erb
  <header>
  <nav class="h-100 navbar navbar-expand-lg navbar-light bg-light pl-5">
    <% if logged_in? %>
      <%= link_to "ListApp", current_user, class: "navbar-brand" %>
    <% else %>  
      <%= link_to "ListApp", root_path, class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"  aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="justify-content-end collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-5">
       <% if logged_in? %>
        <li><%= link_to "Your Lists", current_user, class: "nav-link" %></li>
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="  false">
          Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item"%>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, method: :delete ,class: "dropdown-item"%>
          </div>
        </li>
       <% else %>
        <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link"%></li> 
       <% end %>
     </ul>
   </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title_method(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div class="p-0 container-fluid">
          <%= render 'layouts/header' %>
            <div id="div-error" class="container error">
              <% flash.each do |msg_type, msg| %>
                <div class="m-2 alert alert-dismissible fade show alert-<%= msg_type %>">
                  <%= msg %>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"> 
                    <span aria-hidden="true">&times;</span>
                  </button>    
                  </div>
              <% end %>
            </div>
          <%= yield %>
          <%= render 'layouts/footer' %>
        </div>
  </body>
</html>